### ISSUE TITLE
Followed make it go, but I get nothing on 4200

### ISSUE THREAD

**Issue by andrewgy8** [dancancro/great-big-angular2-example#1]
Looks like a great repo!

However i followed you make it go section, and all I see on localhost 4200 is "Loading...". On `npm run dev:client` I get these:

```
WARNING in ./src/app/debate/claim/claim.component.ts
38:55-60 "export 'Claim' was not found in '../../core/store/claim/claim.model'

WARNING in ./src/app/debate/claim/claim.component.ts
38:80-85 "export 'Claim' was not found in '../../core/store/claim/claim.model'

WARNING in ./src/app/debate/rebuttal/rebuttal.component.ts
35:55-60 "export 'Claim' was not found in '../../core/store/claim/claim.model'

WARNING in ./src/app/debate/rebuttal/rebuttal.component.ts
35:80-85 "export 'Claim' was not found in '../../core/store/claim/claim.model'

WARNING in ./src/app/debate/rebuttal/rebuttal.component.ts
39:55-63 "export 'Rebuttal' was not found in '../../core/store/rebuttal/rebuttal.model'

WARNING in ./src/app/debate/rebuttal/rebuttal.component.ts
39:83-91 "export 'Rebuttal' was not found in '../../core/store/rebuttal/rebuttal.model'
webpack: Compiled with warnings.
```

I am suppose to see a UI when I nav to 4200 right?

**Comment by dancancro** [comment]
Hi Andrew. Welcome to this project! You're my first customer :)

This one has confounded me. It looks like I made your change to the `entityactions` branch that I'm working on today but it has the same problem. So I'm puzzled. I had the same problem [3 months ago](http://stackoverflow.com/questions/40513798/untrue-not-found-warnings-in-angular-cli-webpack-project).

However, in spite of the warnings, the app does run. Does it run for you?

Right now, I'm waist deep in updating angular-cli loveliness. Maybe that'll fix it.

**Comment by dancancro** [comment]
Unfortunately updating angular-cli didn't fix the problem. It did however start displaying these incorrect warnings as an overlay on the page so you can't use the app.

To turn off this new overlay, you need to change line 140 of node_modules/@angular/cli/tasks/serve.js from 
```
      overlay: serveTaskOptions.target === 'development'
```
to 
```
      overlay: false // serveTaskOptions.target === 'development'
```

**Comment by andrewgy8** [comment]
Hmmm, I think the warnings are seerate from the loading issue. I submitted a pull request which updated the side-nav according to [this](https://github.com/angular/material.angular.io/pull/89).  It seemed to fix the issue.

**Comment by dancancro** [comment]
Strange. I pushed a bunch of changes yesterday including [that one](https://github.com/dancancro/great-big-angular2-example/blob/master/src/app/core/navigator/layout.component.ts#L7), but I'm still getting this warning problem. Would you mind giving it a try?
