### ISSUE TITLE
Lazy loading and providing services

### ISSUE THREAD

**Issue by picosam** [dancancro/great-big-angular2-example#7]
Hello, this is a question actually: is the Books module lazy loaded? If so, does this mean that `GoogleBooksService` is not being loaded until the `BooksModule` is?

**Comment by dancancro** [comment]
Right.  This line says don't load the BooksModule until the /books route is requested
https://github.com/dancancro/great-big-angular2-example/blob/master/src/app/app.routing.ts#L10

And this line says the BooksModule, when loaded, makes available the GoogleBooksService to whatever components are declared in BooksModule
https://github.com/dancancro/great-big-angular2-example/blob/master/src/app/books/books.module.ts#L58

Another module could also have GoogleBooksService as a provider and load it, but for now this is the only one that does.

I think.
